<a href="https://colab.research.google.com/github/benjaminjeremiah/testgit/blob/master/Lesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = [6,7,8,9]

In [4]:
print(type(arr)) #prints <class 'list'>

<class 'list'>


In [5]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(4,)
int64


In [6]:
print(a.ndim)

1


In [7]:
b = np.array([[1,2,3], [4,5,6,]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b.ndim)

2


In [9]:
b.shape

(2, 3)

In [10]:
np.random.random((2,3)) 

array([[0.69309826, 0.33121381, 0.92856533],
       [0.83560704, 0.18223515, 0.26554734]])

In [11]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])

In [12]:
d = np.array([[4.0,5.0,6.0], [9.0,8.0,7.0]])

In [13]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [14]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [15]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [16]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [17]:
d[1, 0:2] = array([9., 8.])

NameError: ignored

In [18]:
e = np.array([[10,11,12], [13,14,15], [16,17,18], [19,20,21]])

In [21]:
e[:3, :2] = array([[10,11], [13,14], [16,17]])

NameError: ignored